### ISSUE TITLE
Calculate directly from HTML

### ISSUE THREAD

**Issue by jcoolrace** [jcoolrace/grade-calculator#1]
Grades are available through an online interface, so why not just input all the source code and grab all the data we need from it?

[https://docs.python.org/3.6/library/html.parser.html](https://docs.python.org/3.6/library/html.parser.html)

- [x]  Uncategorized
- [x]  Categorized

**Comment by JaeivanRomero** [comment]
I don't know man. I think you're going to make alot of money selling this to the school. This is so a1 stuff, dont' forget about me when you're famous.

**Comment by jcoolrace** [comment]
Ended up using [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/) to extract all the information needed. Probably could be made more efficient, but it successfully performs as intended.
